<a href="https://colab.research.google.com/github/evliyaaa/DeepLearning-ProjectHub/blob/main/PyTorch_DeepLearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
# Import PyTorch
import torch

list_a = [1, 2, 3, 4]

# Create a tensor from list_a
tensor_a = torch.tensor(list_a)

# Display the tensor device
print(tensor_a.device)

# Display the tensor data type
print(tensor_a.dtype)

cpu
torch.int64


In [17]:
import numpy as np
array_a = np.array([[1, 1, 1], [2, 3, 4], [4, 5, 6]])
array_b = np.array([[7, 5, 4], [2, 2, 8], [6, 3, 8]])

In [18]:
# Create two tensors from the arrays
tensor_a = torch.tensor(array_a)
tensor_b = torch.tensor(array_b)

# Subtract tensor_b from tensor_a
tensor_c = tensor_a - tensor_b

# Multiply each element of tensor_a with each element of tensor_b
tensor_d = tensor_a * tensor_b

# Add tensor_c with tensor_d
tensor_e = tensor_c + tensor_d
print(tensor_e)

tensor([[ 1,  1,  1],
        [ 4,  7, 28],
        [22, 17, 46]])


## Sequential Linear model creation

In [19]:
import torch
import torch.nn as nn

input_tensor = torch.Tensor([[2, 3, 6, 7, 9, 3, 2, 1]])

# Implement a small neural network with exactly two linear layers
model = nn.Sequential(nn.Linear(8,5 ),
                      nn.Linear(5, 1)
                     )

output = model(input_tensor)
print(output)

tensor([[-2.1617]], grad_fn=<AddmmBackward0>)


Sigmoid and Softmax can be respectively used in classification tasks: Sigmoid in Binary and Softman is in N-dimentional classes. Which commanly used as the last step of nn.Sequential().

In [20]:
score = torch.tensor([[0.8]])

# Create a sigmoid function and apply it on the score tensor
sigmoid = nn.Sigmoid()
probability = sigmoid(score)
print(probability)

scores = torch.tensor([[1.0, -6.0, 2.5, -0.3, 1.2, 0.8]])

# Create a softmax function and apply it on the score tensor
softmax = nn.Softmax(dim=-1)
probabilities = softmax(scores)
print(probabilities)

tensor([[0.6900]])
tensor([[1.2828e-01, 1.1698e-04, 5.7492e-01, 3.4961e-02, 1.5669e-01, 1.0503e-01]])


### Building a binary classifier in PyTorch

In [21]:
input_tensor = torch.Tensor([[3, 4, 6, 2, 3, 6, 8, 9]])

# Implement a small neural network for binary classification
model = nn.Sequential(
  nn.Linear(8, 1),
  nn.Sigmoid()
)

output = model(input_tensor)
print(output)

tensor([[0.4358]], grad_fn=<SigmoidBackward0>)


### Regression

In [22]:
input_tensor = torch.Tensor([[3, 4, 6, 7, 10, 12, 2, 3, 6, 8, 9]])

# Implement a neural network with exactly four linear layers
model = nn.Sequential(nn.Linear(11, 6),
                nn.Linear(6, 4),
                nn.Linear(4, 2),
                nn.Linear(2, 1))
output = model(input_tensor)
print(output)

tensor([[0.3510]], grad_fn=<AddmmBackward0>)


### From regression to multi-class classification

In [23]:
input_tensor = torch.Tensor([[3, 4, 6, 7, 10, 12, 2, 3, 6, 8, 9]])

# Update network below to perform a multi-class classification with four labels
model = nn.Sequential(
  nn.Linear(11, 20),
  nn.Linear(20, 12),
  nn.Linear(12, 6),
  nn.Linear(6, 4),
  nn.Softmax(dim=-1)
)

output = model(input_tensor)
print(output)

tensor([[0.4236, 0.1537, 0.2618, 0.1610]], grad_fn=<SoftmaxBackward0>)


## Loss Calculation

In [24]:
import torch.nn.functional as F

y = [2]
scores = torch.tensor([[0.1, 6.0, -2.0, 3.2]])

# Create a one-hot encoded vector of the label y
one_hot_label = F.one_hot(torch.tensor(y), scores.shape[1])

# Create the cross entropy loss function
criterion = nn.CrossEntropyLoss()

# Calculate the cross entropy loss
loss = criterion(scores.double(), one_hot_label.double())
print(loss)

tensor(8.0619, dtype=torch.float64)


In [25]:
preds = torch.tensor([[1.3568, 0.2272]])

target = torch.tensor([[1., 0.]])

criterion = nn.CrossEntropyLoss()

# Calculate the loss
loss = criterion(preds, target)

# Compute the gradients of the loss

#model = loss.backward()
# Display gradients of the weight and bias tensors in order
#print(weight.grad)
#print(bias.grad)


Accesing the weights and biases in the loss

In [26]:
model = nn.Sequential(nn.Linear(16, 8),
                      nn.Linear(8, 8),
                      nn.Linear(8, 2))

# Access the weight of the first linear layer
weight_0 = model[0].weight

# Access the bias of the second linear layer
bias_1 = model[2].bias

In [27]:
lr = 0.001

weight0 = model[0].weight
weight1 = model[1].weight
weight2 = model[2].weight

# Access the gradients of the weight of each linear layer
grads0 = model[0].weight.grad
grads1 = model[1].weight.grad
grads2 = model[2].weight.grad

# Update the weights using the learning rate and the gradients
#weight0 = weight0 - lr * grads0
#weight1 = weight1 - lr * grads1
#weight2 = weight2 - lr * grads2

### Using the PyTorch optimizer

In [28]:
import torch.optim as optim
# Create the optimizer
optimizer = optim.SGD(model.parameters(), lr=0.001)

loss = criterion(preds, target)
#loss.backward()

# Update the model's parameters using the optimizer
optimizer.step()

In [29]:
y_hat = np.array(10)
y = np.array(1)

# Calculate the MSELoss using NumPy
mse_numpy = np.mean((y_hat - y)**2)

# Create the MSELoss function
criterion = nn.MSELoss()

# Calculate the MSELoss using the created loss function
mse_pytorch = criterion(torch.tensor(y_hat).float(), torch.tensor(y).float())
print(mse_pytorch)

tensor(81.)


from torch.utils.data import TensorDataset
from torch.utils.data import DataLoader

dataset = TensorDataset(torch.tensor(features).float(), torch.tensor(target).float())
dataloader = DataLoader(dataset, batch_size=4, shuffle=True)
model = nn.Sequential(nn.Linear(4, 2),
                      nn.Linear(2, 1))
# Create the loss and optimizer
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.001)

## Discovering activation functions between layers

### nn.Relu() Rectified Linear Unit-> is f(x) = max(x, 0)
### nn.LeakyRelu(negative_slope=0.05) -> positive input the same as Relu for negative input multiply the input with coefficient(defoult=0.01).

In [30]:
# Create a ReLU function with PyTorch
relu_pytorch = nn.ReLU()

# Apply your ReLU function on x, and calculate gradients
x = torch.tensor(-1.0, requires_grad=True)
y = relu_pytorch(x)
y.backward()

# Print the gradient of the ReLU function for x
gradient = x.grad
print(gradient)

tensor(0.)


In [31]:
# Create a leaky relu function in PyTorch
leaky_relu_pytorch = nn.LeakyReLU(negative_slope=0.05)

x = torch.tensor(-2.0)
# Call the above function on the tensor x
output = leaky_relu_pytorch(x)
print(output)

tensor(-0.1000)


### Counting the number of parameters

In [32]:
model = nn.Sequential(nn.Linear(16, 4),
                      nn.Linear(4, 2),
                      nn.Linear(2, 1))

total = 0

# Calculate the number of parameters in the model
for parameter in model.parameters():
  total += parameter.numel()

Manipulating the capacity of a network
In this exercise, you will practice creating neural networks with different capacities. The capacity of a network reflects the number of parameters in said network. To help you, a calculate_capacity() function has been implemented, as follows:

In [33]:
def calculate_capacity(model):
  total = 0
  for p in model.parameters():
    total += p.numel()
  return total

In [34]:
n_features = 8
n_classes = 2

input_tensor = torch.Tensor([[3, 4, 6, 2, 3, 6, 8, 9]])

# Create a neural network with more than 120 parameters
model = nn.Sequential(nn.Linear(n_features, 7),
                  nn.Linear(7, 6),
                  nn.Linear(6, 5),
                  nn.Linear(5, n_classes))

output = model(input_tensor)

print(calculate_capacity(model))


# Create a neural network with less than 120 parameters
model = nn.Sequential(nn.Linear(n_features, 6),
                nn.Linear(6, 4),
                nn.Linear(4, n_classes))
output = model(input_tensor)

print(calculate_capacity(model))

158
92


## Layer initialization

In [35]:
layer0 = nn.Linear(16, 32)
layer1 = nn.Linear(32, 64)

# Use uniform initialization for layer0 and layer1 weights
nn.init.uniform_(layer0.weight)
nn.init.uniform_(layer1.weight)

model = nn.Sequential(layer0, layer1)

## Freezing layers of a model

In [36]:
for name, param in model.named_parameters():

    # Check if the parameters belong to the first layer
    if name == '0.weight' or name == '0.bias':

        # Freeze the parameters
        param.requires_grad = False

    # Check if the parameters belong to the second layer
    if name == '1.weight' or name == '1.bias':

        # Freeze the parameters
        param.requires_grad = False

## Transfer learning and fine-tuningTransfer learning: reusing a model trained on a first task for a second similar task, toaccelerate the training process.

In [37]:
layer = nn.Linear(64, 128)
torch.save(layer, 'layer.pth')
new_layer = torch.load('layer.pth')

In [38]:
import numpy as np
import torch
from torch.utils.data import TensorDataset

np_features = np.array(np.random.rand(12, 8))
np_target = np.array(np.random.rand(12, 1))

# Convert arrays to PyTorch tensors
torch_features = torch.tensor(np_features)
torch_target = torch.tensor(np_target)

# Create a TensorDataset from two tensors
dataset = TensorDataset(torch_features, torch_target)

# Return the last element of this dataset
print(dataset[-1])

(tensor([0.2245, 0.6936, 0.0808, 0.0734, 0.9029, 0.9321, 0.6817, 0.2427],
       dtype=torch.float64), tensor([0.7108], dtype=torch.float64))


In [39]:
from google.colab import files

uploaded = files.upload()

Saving water_potability.csv to water_potability (2).csv


In [40]:
import pandas as pd
df = pd.read_csv('water_potability.csv')
df.tail()

ph  Hardness    Solids  Chloramines   Sulfate  Conductivity  \
2006  0.636224  0.580511  0.277748     0.418063  0.522486      0.342184   
2007  0.470143  0.548826  0.301347     0.538273  0.498565      0.231359   
2008  0.817826  0.087434  0.656389     0.670774  0.369089      0.431872   
2009  0.424187  0.464092  0.459656     0.541633  0.615572      0.388360   
2010  0.322425  0.492891  0.841409     0.492136  0.656047      0.588709   

      Organic_carbon  Trihalomethanes  Turbidity  Potability  
2006        0.310364         0.402799   0.627156           1  
2007        0.565061         0.175889   0.395061           1  
2008        0.563265         0.285745   0.578674           1  
2009        0.397780         0.449156   0.440004           1  
2010        0.471422         0.503458   0.591867           1

In [41]:
from torch.utils.data import DataLoader
import torch.nn as nn

# Load the different columns into two PyTorch tensors
features = torch.tensor(np.array(
  df[['ph', 'Sulfate', 'Conductivity', 'Organic_carbon']])).float()
target = torch.tensor(np.array(
  df['Potability'])).float()

# Create a dataset from the two generated tensors
dataset = TensorDataset(features, target)

# Create a dataloader using the above dataset
dataloader = DataLoader(dataset, shuffle=True, batch_size=2)
x, y = next(iter(dataloader))

# Create a model using the nn.Sequential API
model = nn.Sequential(nn.Linear(4, 2),
                   nn.Linear(2, 1))
output = model(features)
print(output)

tensor([[-0.2485],
        [-0.1356],
        [-0.1632],
        ...,
        [-0.1583],
        [-0.1498],
        [-0.1296]], grad_fn=<AddmmBackward0>)


### Model Validation

In [42]:
# Set the model to evaluation mode
model.eval()
validation_loss = 0.0

with torch.no_grad():
    for data in dataloader:
        outputs = model(data[0])
        loss = criterion(outputs, data[1])
        validation_loss += loss.item()

# Calculate the mean loss value
validation_loss_epoch = validation_loss / len(dataloader)
print(validation_loss_epoch)

# Set the model back to training mode
model.train()


/usr/local/lib/python3.10/dist-packages/torch/nn/modules/loss.py:535: UserWarning: Using a target size (torch.Size([2])) that is different to the input size (torch.Size([2, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


0.5701470645142267


/usr/local/lib/python3.10/dist-packages/torch/nn/modules/loss.py:535: UserWarning: Using a target size (torch.Size([1])) that is different to the input size (torch.Size([1, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


Sequential(
  (0): Linear(in_features=4, out_features=2, bias=True)
  (1): Linear(in_features=2, out_features=1, bias=True)
)

In [56]:
import torchmetrics
# Create accuracy metric using torch metrics
metric = torchmetrics.Accuracy(task="multiclass", num_classes=3)
for data in dataloader:
    features, labels = data
    outputs = model(features)

    # Calculate accuracy over the batch
    #acc = metric(outputs, target)

# Calculate accuracy over the whole epoch
acc = metric.compute()

# Reset the metric for the next epoch
metric.reset()